### ISSUE TITLE
ReDO finally takes whole image as one region if it iterates enough times.

### ISSUE THREAD

**Issue by datong-new** [mickaelChen/ReDO#3]
![out_89500](https://user-images.githubusercontent.com/22614443/68558410-34656880-0474-11ea-89df-59544fb0e0a0.png)

As above image shows, when I iterate the training 89500 times with batch size 15, the proposal mask may be almost either empty or the whole image. And the generator prefers to generate a completely new image or do nothing.

Are there some mistakes in my training process. How to avoid this problem?

Thanks for any reply!

**Comment by mickaelChen** [comment]
Yes, unfortunately, ReDO is still quite unstable. I usually early stop and train for about 20k to 40k iterations.
I added a few comments in the readme regarding this.

Besides, I have never tried with batch smaller than 20 so I'm not sure it would behave exactly the same.

**Comment by mickaelChen** [comment]
I'm closing the issue, feel free to reopen it for any follow-up question or comment.
