### ISSUE TITLE
error while testing on the custom data

### ISSUE THREAD

**Issue by MNCTTY** [mickaelChen/ReDO#4]
Hi! Thank you for your code and article

I tried to test and see some results, but faced an error;

```
File "/Users/mnctty/Desktop/ReDO/datasets.py", line 76, in __getitem__
    self.files[idx,1]+'.jpg'))
IndexError: index 1 is out of bounds for axis 1 with size 1
```

I ran this code:
```
python3 example_load_pretrained.py --statePathM netM_state.pth --dataroot ../MRT_data/ --device cpu
```
the structure of MRT_data/ is 3 folders with imgs in each and test.txt file, where their names listed

can you say me please what I should fix to run the test?

**Comment by mickaelChen** [comment]
Hi,

Data is loaded using subclasses of torch.utils.data.Dataset implemented in datasets.py.
Each class corresponds to one of the datasets we use.

It would seem your test.txt file is formated differently than expected.

You should probably implement a different Dataset subclass for your custom data and then instantiate it in train.py (lines 114-177).
